name: 'Update version'

on: 
  pull_request:
    types:
      - opened
    branches:
      - main

permissions:
  contents: write

jobs:
  major_version:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'FREEZE') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          version-type: 'major'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  minor_version:
    if: ${{ github.event.pull_request.merged == true && !startsWith(github.event.pull_request.title, 'FREEZE') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          patch-wording: 'fix,patch,fixing,patching'
          minor-wording: 'improvement,'
          default: 'minor'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
